// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"character-data-microservice/models"
)

// GetSkillOKCode is the HTTP code returned for type GetSkillOK
const GetSkillOKCode int = 200

/*GetSkillOK Returns specified skill

swagger:response getSkillOK
*/
type GetSkillOK struct {

	/*
	  In: Body
	*/
	Payload *models.Skill `json:"body,omitempty"`
}

// NewGetSkillOK creates GetSkillOK with default headers values
func NewGetSkillOK() *GetSkillOK {

	return &GetSkillOK{}
}

// WithPayload adds the payload to the get skill o k response
func (o *GetSkillOK) WithPayload(payload *models.Skill) *GetSkillOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get skill o k response
func (o *GetSkillOK) SetPayload(payload *models.Skill) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSkillOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetSkillDefault Generic error response

swagger:response getSkillDefault
*/
type GetSkillDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetSkillDefault creates GetSkillDefault with default headers values
func NewGetSkillDefault(code int) *GetSkillDefault {
	if code <= 0 {
		code = 500
	}

	return &GetSkillDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get skill default response
func (o *GetSkillDefault) WithStatusCode(code int) *GetSkillDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get skill default response
func (o *GetSkillDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get skill default response
func (o *GetSkillDefault) WithPayload(payload *models.Error) *GetSkillDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get skill default response
func (o *GetSkillDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSkillDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
