// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetClassParams creates a new GetClassParams object
// no default values defined in spec.
func NewGetClassParams() GetClassParams {

	return GetClassParams{}
}

// GetClassParams contains all the bound params for the get class operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetClass
type GetClassParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	PlayerID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetClassParams() beforehand.
func (o *GetClassParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rPlayerID, rhkPlayerID, _ := route.Params.GetOK("playerId")
	if err := o.bindPlayerID(rPlayerID, rhkPlayerID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPlayerID binds and validates parameter PlayerID from path.
func (o *GetClassParams) bindPlayerID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("playerId", "path", "int64", raw)
	}
	o.PlayerID = value

	return nil
}
