// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Character Data Microservice
//
//  Microservice for managing character data in online games
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
