// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Microservice for managing character data in online games",
    "title": "Character Data Microservice",
    "version": "1.0.0"
  },
  "paths": {
    "/class/{playerId}": {
      "get": {
        "operationId": "GetClass",
        "responses": {
          "200": {
            "description": "Returns players class",
            "schema": {
              "$ref": "#/definitions/class"
            }
          },
          "default": {
            "description": "Generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "playerId",
          "in": "path",
          "required": true
        }
      ]
    },
    "/item/{itemId}": {
      "get": {
        "operationId": "GetItem",
        "responses": {
          "200": {
            "description": "Returns specified item",
            "schema": {
              "$ref": "#/definitions/item"
            }
          },
          "default": {
            "description": "Generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "itemId",
          "in": "path",
          "required": true
        }
      ]
    },
    "/items": {
      "get": {
        "operationId": "GetItems",
        "responses": {
          "200": {
            "description": "List owned items",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/item"
              }
            }
          },
          "default": {
            "description": "Generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/skill/{skillId}": {
      "get": {
        "operationId": "GetSkill",
        "responses": {
          "200": {
            "description": "Returns specified skill",
            "schema": {
              "$ref": "#/definitions/skill"
            }
          },
          "default": {
            "description": "Generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "skillId",
          "in": "path",
          "required": true
        }
      ]
    },
    "/skills": {
      "get": {
        "operationId": "GetSkills",
        "responses": {
          "200": {
            "description": "Returns list of skills",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/skill"
              }
            }
          },
          "default": {
            "description": "Generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "class": {
      "type": "object",
      "required": [
        "description"
      ],
      "properties": {
        "abilities": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/skill"
          }
        },
        "description": {
          "type": "string"
        },
        "identifier": {
          "type": "integer"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "item": {
      "type": "object",
      "required": [
        "identifier",
        "description"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "identifier": {
          "type": "integer"
        }
      }
    },
    "skill": {
      "type": "object",
      "required": [
        "identifier"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "identifier": {
          "type": "integer"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Microservice for managing character data in online games",
    "title": "Character Data Microservice",
    "version": "1.0.0"
  },
  "paths": {
    "/class/{playerId}": {
      "get": {
        "operationId": "GetClass",
        "responses": {
          "200": {
            "description": "Returns players class",
            "schema": {
              "$ref": "#/definitions/class"
            }
          },
          "default": {
            "description": "Generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "playerId",
          "in": "path",
          "required": true
        }
      ]
    },
    "/item/{itemId}": {
      "get": {
        "operationId": "GetItem",
        "responses": {
          "200": {
            "description": "Returns specified item",
            "schema": {
              "$ref": "#/definitions/item"
            }
          },
          "default": {
            "description": "Generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "itemId",
          "in": "path",
          "required": true
        }
      ]
    },
    "/items": {
      "get": {
        "operationId": "GetItems",
        "responses": {
          "200": {
            "description": "List owned items",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/item"
              }
            }
          },
          "default": {
            "description": "Generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/skill/{skillId}": {
      "get": {
        "operationId": "GetSkill",
        "responses": {
          "200": {
            "description": "Returns specified skill",
            "schema": {
              "$ref": "#/definitions/skill"
            }
          },
          "default": {
            "description": "Generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "skillId",
          "in": "path",
          "required": true
        }
      ]
    },
    "/skills": {
      "get": {
        "operationId": "GetSkills",
        "responses": {
          "200": {
            "description": "Returns list of skills",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/skill"
              }
            }
          },
          "default": {
            "description": "Generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "class": {
      "type": "object",
      "required": [
        "description"
      ],
      "properties": {
        "abilities": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/skill"
          }
        },
        "description": {
          "type": "string"
        },
        "identifier": {
          "type": "integer"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "item": {
      "type": "object",
      "required": [
        "identifier",
        "description"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "identifier": {
          "type": "integer"
        }
      }
    },
    "skill": {
      "type": "object",
      "required": [
        "identifier"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "identifier": {
          "type": "integer"
        }
      }
    }
  }
}`))
}
